version: '3.8'

services:
  app:
    image: '        taskmanagementsystem'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: TaskManagementSystem
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tmsystem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: saviyadav@13
      JWT_SECRET: secretkey
      JWT_EXPIRATION: 86400000
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: saviyadav@13
      MYSQL_DATABASE: tmsystem
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
